package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Degrees;
import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;

import java.util.List;
import java.util.Optional;
import java.util.function.Supplier;

import org.littletonrobotics.junction.Logger;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.controls.PositionVoltage;
import com.ctre.phoenix6.controls.VoltageOut;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.FieldCentricFacingAngle;

import choreo.auto.AutoFactory;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.Unit;
import edu.wpi.first.units.Units;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.Time;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.FunctionalCommand;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.ParallelCommandGroup;
import edu.wpi.first.wpilibj2.command.RunCommand;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.RobotContainer;
import frc.robot.LimelightHelpers.PoseEstimate;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.lib.BLine.FollowPath;
import frc.robot.lib.BLine.Path;
import frc.robot.oi.BaseOI;
import frc.robot.vision.Limelight;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    /// Deadband to apply to translation requests
    private static final double TRANSLATION_DEADBAND = 0.1;

    /// Deadband to apply to rotation requests
    private static final double ROTATION_DEADBAND = 0.15;

    /// Scalar to help offset drive skew
    private static final double SKEW_COMPENSATION_SCALAR = -0.03;

    /// Drivetrain States
    public enum WantedState {
        SYS_ID,
        TELEOP_DRIVE,
        AUTONOMOUS,
        ROTATION_LOCK,
        DRIVE_TO_POINT,
        INTAKE_GROUND,
        IDLE,
        BRAKE
    }

    public enum SystemState {
        SYS_ID,
        TELEOP_DRIVE,
        AUTONOMOUS,
        ROTATION_LOCK,
        DRIVE_TO_POINT,
        INTAKE_GROUND,
        IDLE,
        BRAKE
    }

    /// Current System State
    private SystemState mCurrentState = SystemState.IDLE;
    /// Targeted System State
    private WantedState mDesiredState = WantedState.IDLE;
    /// Swerve Drive State
    private SwerveDriveState mCurrentSwerveState = new SwerveDriveState();

    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    // TODO: move this to constants
    private final double hubX = 4.625594;
    private final double hubY = 8.07 / 2;
    private final double hubXOffset = 7.2898;

    private final double maxSpeed = TunerConstants.kSpeedAt12Volts.in(MetersPerSecond);
    private final double maxAngularRate = Units.RotationsPerSecond.of(0.75)
            .in(Units.RadiansPerSecond); // 3/4 of a rotation per second max angular velocity

    public final FieldCentricFacingAngle driveAndPoint = new FieldCentricFacingAngle()
            .withDeadband(maxSpeed * 0.1) // Add a 10% deadband
            .withRotationalDeadband(maxAngularRate * 0.1)
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage) // Use open-loop control for drive motors
            .withDesaturateWheelSpeeds(true)
            .withHeadingPID(8.0, 0.0, 0.25);

    /* Setting up bindings for necessary control of the swerve drive platform */
    private final SwerveRequest.FieldCentric drive = new SwerveRequest.FieldCentric()
            .withDeadband(maxSpeed * 0.1)
            .withRotationalDeadband(maxAngularRate * 0.1) // Add a 10% deadband
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage) // Use open-loop control for drive motors
            .withDesaturateWheelSpeeds(true);

    private final SwerveRequest.ApplyFieldSpeeds driveApplyFieldSpeeds = new SwerveRequest.ApplyFieldSpeeds()
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage) // Use open-loop control for drive motors
            .withDesaturateWheelSpeeds(true);

    private final SwerveRequest.SwerveDriveBrake brake = new SwerveRequest.SwerveDriveBrake();

    private double lastUpdate = Timer.getFPGATimestamp();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
            new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization =
            new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization =
            new SwerveRequest.SysIdSwerveRotation();

    private FollowPath.Builder pathBuilder;
    private AutoFactory autoFactory;
    private final PIDController xController = new PIDController(5, 0.0, 0);
    private final PIDController headingController = new PIDController(5, 0.0, 0.2);
    private final PIDController adjustY = new PIDController(0.5, 0, 0);

    private final SwerveRequest.ApplyRobotSpeeds applyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds()
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage); // Use open-loop control for drive motors

    private ChassisSpeeds currentChassisSpeeds = new ChassisSpeeds();

    public final Limelight limelightLeft = new Limelight("limelight-left");
    //shooter
    public final Limelight limelightRight = new Limelight("limelight-right");
    public final Limelight limelightBack = new Limelight("limelight-back");
    //intake
    public final Limelight limelightForward = new Limelight("limelight-forward");

    public final Limelight[] limelights = {limelightRight, limelightBack, limelightForward, limelightForward};

    private double xSpeed;
    private double xSpeedPid;
    private double ySpeed;
    private double ySpeedPid;
    private double thetaSpeed;
    private double thetaPid;
    private PIDController centerPIDx;
    private PIDController centerPIDy;
    private PIDController centerRotaionPid;
    private Pose2d robotPoseTagspace;
    private Pose2d tagPoseRobotspace;
    private int tag;
    private List<Integer> tagsToCheck;
    

    // Choreo PID controllers have to be created in our code
    private final PIDController choreoXController = new PIDController(5, 0, 0);
    private final PIDController choreoYController = new PIDController(5, 0, 0);
    private final PIDController choreoHeadingController = new PIDController(5, 0, 0.2);

    private Rotation2d snapToHeading = (!DriverStation.getAlliance().isEmpty()
                    && DriverStation.getAlliance().get() == Alliance.Red)
            ? new Rotation2d(Math.PI)
            : new Rotation2d(0);

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        CommandScheduler.getInstance().registerSubsystem(this);

        if (Utils.isSimulation()) {
            startSimThread();
        }
        // B-Line path builder
        pathBuilder = initializeFollowPathBuilder();
        autoFactory = initializeChoreoAutoFactory();
        headingController.enableContinuousInput(-Math.PI, Math.PI);
    }

    public FollowPath.Builder getPathBuilder() {
        return pathBuilder;
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        CommandScheduler.getInstance().registerSubsystem(this);

        if (Utils.isSimulation()) {
            startSimThread();
        }
        // B-Line path builder
        pathBuilder = initializeFollowPathBuilder();
        autoFactory = initializeChoreoAutoFactory();
        headingController.enableContinuousInput(-Math.PI, Math.PI);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(
                drivetrainConstants,
                odometryUpdateFrequency,
                odometryStandardDeviation,
                visionStandardDeviation,
                modules);
        CommandScheduler.getInstance().registerSubsystem(this);

        if (Utils.isSimulation()) {
            startSimThread();
        }

        // B-Line path builder
        pathBuilder = initializeFollowPathBuilder();
        autoFactory = initializeChoreoAutoFactory();
        headingController.enableContinuousInput(-Math.PI, Math.PI);
    }

    // Create a reusable builder with your robot's configuration
    private FollowPath.Builder initializeFollowPathBuilder() {
        return new FollowPath.Builder(
                        this, // The drive subsystem to require
                        this::getCurrentPose2D, // Supplier for current robot pose
                        this::getCurrentChassisSpeeds, // Supplier for current speeds
                        this::controlRobotDrivetrainAutonomus, // Consumer to drive the robot
                        xController, // Translation PID
                        headingController, // Rotation PID
                        // TODO: Figure this out
                        new PIDController(2.0, 0.0, 0.0) // Cross-track PID
                        )
                .withDefaultShouldFlip() // Auto-flip for red alliance
                .withPoseReset(this::resetPose); // Reset odometry at path start
    }

    private AutoFactory initializeChoreoAutoFactory() {
        return new AutoFactory(
                this::getCurrentPose2D, this::resetPose, this::controlRobotDrivetrainAutonomus, true, this);
    }

    @Override
    public void periodic() {
        // handle state transitions as applicable
        mCurrentState = handleStateTransition();
        // apply the latest state
        applyStates();
        mCurrentSwerveState = this.getStateCopy();
        Logger.recordOutput("Drivetrain/currentPose", mCurrentSwerveState.Pose);
        Logger.recordOutput("Drivetrain/currentState", mCurrentState);

        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }

        // if (mt2 != null) {
        //     Logger.recordOutput("Drivetrain/poseMegatag", mt2.pose);
        //     boolean rejectUpdate = false;

        //     if (mt2.tagCount == 0) {
        //         rejectUpdate = true;
        //     }

        //     Logger.recordOutput("Drivetrain/RejectUpdate", rejectUpdate);
        //     if (!rejectUpdate) {
        //         this.setVisionMeasurementStdDevs(VecBuilder.fill(.7, .7, 9999999));
        //         this.addVisionMeasurement(mt2.pose, mt2.timestampSeconds);
        //     }

        // }
        for(Limelight limelight : limelights){
			PoseEstimate mt2 = limelight.getPoseMegatag2();
			if (mt2 != null) {
				Logger.recordOutput("Drivetrain/poseMegatag"+limelight.getLimelightName(), mt2.pose);

				// if our angular velocity is greater than 720 degrees per second, ignore vision updates or if it doesnt see any tags		
				Logger.recordOutput("Drivetrain/doRejectUpdate" +limelight.getLimelightName(), isUpdateable(mt2));
				if(isUpdateable(mt2)) {
                    //VecBuilder.fill(0.7,0.7,9999999) default trust
					this.setVisionMeasurementStdDevs(limelight.getLimelightTrust());
					this.addVisionMeasurement(
						mt2.pose,
						mt2.timestampSeconds);
				}
			}
		}

        Logger.recordOutput("Drivetrain/Pose", mCurrentSwerveState.Pose);
        Logger.recordOutput("Drivetrain/Imumode", limelightLeft.getImuMode());
        PoseEstimate mt1 = this.limelightLeft.getPoseMegatag1();
        if (mt1 != null) {
            Logger.recordOutput("Drivetrain/Mt1", mt1.pose);
        }
    }

    public boolean isUpdateable(PoseEstimate posEst) {
		// if (Math.abs(this.gyroInputs.yawVelocityRadPerSec.in(Units.DegreesPerSecond)) > 720) { 
		// 	return false;
		// }
		if (posEst.tagCount == 0) {
			return false;
		}
		if (Double.isNaN(posEst.pose.getX()) || Double.isNaN(posEst.pose.getY()) || Double.isInfinite(posEst.pose.getX()) || Double.isInfinite(posEst.pose.getY())) {
			return false;
		}
		if (Double.isNaN(posEst.pose.getRotation().getDegrees())|| Double.isInfinite(posEst.pose.getRotation().getDegrees())) {
			return false;
		}
		if (posEst.pose.getX() > 100d || posEst.pose.getY() > 100d) {
			return false;
		}
		
		return true;
	}

    private SystemState handleStateTransition() {
        return switch (mDesiredState) {
            case SYS_ID -> SystemState.SYS_ID;
            case TELEOP_DRIVE -> SystemState.TELEOP_DRIVE;
            case AUTONOMOUS -> {
                yield SystemState.AUTONOMOUS;
                // if (mCurrentState != SystemState.CHOREO_PATH) {
                //     choreoTimer.restart();
                //     choreoSampleToBeApplied = desiredChoreoTrajectory.sampleAt(choreoTimer.get(), false);
                //     yield SystemState.CHOREO_PATH;
                // } else {
                //     choreoSampleToBeApplied = desiredChoreoTrajectory.sampleAt(choreoTimer.get(), false);
                //     yield SystemState.CHOREO_PATH;
                // }
            }
            case ROTATION_LOCK -> SystemState.ROTATION_LOCK;
            case DRIVE_TO_POINT -> SystemState.DRIVE_TO_POINT;
            case BRAKE -> SystemState.BRAKE;
            case INTAKE_GROUND -> SystemState.INTAKE_GROUND;
            default -> SystemState.IDLE;
        };
    }

    private void applyStates() {
        switch (mCurrentState) {
            default:
            case SYS_ID:
                break;
            case TELEOP_DRIVE: {
                this.setControl((driveApplyFieldSpeeds.withSpeeds(calculateSpeedsBasedOnJoystickInputs(RobotContainer.getInstance().driverOI))));
                // FIXME: this needs to be our internal call...
                // applyRequest(new SwerveRequest.ApplyFieldSpeeds()
                //         .withSpeeds(calculateSpeedsBasedOnJoystickInputs())
                //         .withDriveRequestType(SwerveModule.DriveRequestType.OpenLoopVoltage)
                //         .withDesaturateWheelSpeeds(true));
                // joystickDrive(RobotContainer.getInstance().driverOI);
                break;
            }
            case AUTONOMOUS: {
                // TODO: handle autonomous updates... may need to synchronize at some point
                // currently a no-op since the auto factory commands directly call controlRobotDrivetrainAutonomus
                break;
            }
            case ROTATION_LOCK: {
                this.setControl((driveAndPoint
                            .withVelocityX(calculateSpeedsBasedOnJoystickInputs(RobotContainer.getInstance().driverOI).vxMetersPerSecond)
                            .withVelocityY(calculateSpeedsBasedOnJoystickInputs(RobotContainer.getInstance().driverOI).vyMetersPerSecond)
                            .withTargetDirection(snapToHeading)));
                // FIXME: this needs to be our internal call...
                aimAtHubAndMove(RobotContainer.getInstance().driverOI, 0);
                // io.setSwerveState(driveAtAngle
                //         .withVelocityX(calculateSpeedsBasedOnJoystickInputs().vxMetersPerSecond)
                //         .withVelocityY(calculateSpeedsBasedOnJoystickInputs().vyMetersPerSecond)
                //         .withTargetDirection(desiredRotationForRotationLockState));
                break;
            }
            case DRIVE_TO_POINT:
                // TODO: this is basically CenterLimelight...
                centerLimelight(new Pose2d());
                break;
            case INTAKE_GROUND:
                intakeGround(1);
                break;
            case BRAKE:
                this.setControl(brake);
                break;
            case IDLE:
                this.halt();
                break;
        }
    }

    public void setState(WantedState state) {
        mDesiredState = state;
    }

    public boolean isAtHome() {
        double xCoordinateInInches = mCurrentSwerveState.Pose.getMeasureX().in(Units.Inches);
        Optional<Alliance> alliance = DriverStation.getAlliance();
        switch (alliance.get()) {
            case Red:
                return xCoordinateInInches > (651.22 - 183);
            case Blue:
                return xCoordinateInInches < 183.0;
            default:
                return false;
        }
    }

    public ChassisSpeeds centerLimelight(Distance offsetX, Distance offsetY, Angle offsetTheta, Pose2d targetPose) {
        Pose2d robotPose = this.getCurrentPose2D();
        robotPoseTagspace = robotPose.relativeTo(targetPose);
        tagPoseRobotspace = targetPose.relativeTo(robotPose);
        // xSpeed = tagPoseRobotspace.getX();
        // ySpeed = tagPoseRobotspace.getY();
        // thetaSpeed = tagPoseRobotspace.getRotation().getRadians();
        xSpeed = robotPoseTagspace.getX();
        ySpeed = robotPoseTagspace.getY();
        thetaSpeed = robotPoseTagspace.getRotation().getRadians();
        // xSpeedPid = -centerPIDx.calculate(xSpeed,offsetX.in(Units.Meters));
        // ySpeedPid = -centerPIDy.calculate(ySpeed,offsetY.in(Units.Meters));
        // thetaPid = -centerRotaionPid.calculate(thetaSpeed,offsetTheta.in(Units.Radians));
        xSpeedPid = centerPIDx.calculate(xSpeed, offsetX.in(Units.Meters));
        ySpeedPid = centerPIDy.calculate(ySpeed, offsetY.in(Units.Meters));
        double xSpeedRotated = xSpeedPid * Math.cos(offsetTheta.in(Units.Radians))
                - ySpeedPid * Math.sin(offsetTheta.in(Units.Radians));
        double ySpeedRotated = xSpeedPid * Math.sin(offsetTheta.in(Units.Radians))
                + ySpeedPid * Math.cos(offsetTheta.in(Units.Radians));
        thetaPid = centerRotaionPid.calculate(thetaSpeed, offsetTheta.in(Units.Radians));
        // this.controlRobotDrivetrainAutonomus(new ChassisSpeeds(xSpeedRotated, ySpeedRotated, thetaPid * 1.5));

        var limelight = limelightLeft;
        Logger.recordOutput("Drivetrain/Auto/XSpeed", xSpeed);
        Logger.recordOutput("Drivetrain/Auto/YSpeed", ySpeed);
        Logger.recordOutput("Drivetrain/Auto/Center Is Finished", false);
        Logger.recordOutput("Drivetrain/Auto/XSpeedPid", xSpeedPid);
        Logger.recordOutput("Drivetrain/Auto/YSpeedPid", ySpeedPid);
        Logger.recordOutput("Drivetrain/Auto/limelightHasValidTargets", limelight.hasValidTargets());
        Logger.recordOutput(
                "Drivetrain/Auto/Theta",
                limelight.getBotPose3d_TargetSpace().getRotation().getAngle());
        Logger.recordOutput("Drivetrain/Auto/robotPoseTagSpace", robotPoseTagspace);
        Logger.recordOutput("Drivetrain/Auto/tagPoseRobotSpace", tagPoseRobotspace);
        Logger.recordOutput("Drivetrain/Auto/thetaSpeed", thetaSpeed);
        Logger.recordOutput("Drivetrain/Auto/thetaPid", thetaPid);
        Logger.recordOutput(
                "Drivetrain/Auto/estRotation", this.getCurrentPose2D().getRotation());
        Logger.recordOutput("Drivetrain/Auto/offsetX", offsetX);
        Logger.recordOutput("Drivetrain/Auto/offsetTheta", offsetTheta.in(Units.Radians));

        return new ChassisSpeeds(xSpeedRotated, ySpeedRotated, thetaPid * 1.5);
    }

    public ChassisSpeeds centerLimelight(Pose2d targetPose) {
        return centerLimelight(Units.Inches.of(0), Units.Inches.of(0), Units.Radians.of(0), targetPose);
    }

    // spotless: off
    private ChassisSpeeds calculateSpeedsBasedOnJoystickInputs(BaseOI controllerOI) {
        if (DriverStation.getAlliance().isEmpty()) {
            return new ChassisSpeeds(0, 0, 0);
        }

        double xMagnitude = MathUtil.applyDeadband(-controllerOI.controller.getLeftY(), TRANSLATION_DEADBAND);
        double yMagnitude = MathUtil.applyDeadband(-controllerOI.controller.getLeftX(), TRANSLATION_DEADBAND);
        double angularMagnitude = MathUtil.applyDeadband(-controllerOI.controller.getRightX(), ROTATION_DEADBAND);
        //
        //        xMagnitude = Math.copySign(xMagnitude * xMagnitude, xMagnitude);
        //        yMagnitude = Math.copySign(yMagnitude * yMagnitude, yMagnitude);
        angularMagnitude = Math.copySign(angularMagnitude * angularMagnitude, angularMagnitude);

        boolean isRedAlliance = DriverStation.getAlliance().get() == Alliance.Red;
        double xVelocity = (isRedAlliance ? -xMagnitude * maxSpeed : xMagnitude * maxSpeed);
        double yVelocity = (isRedAlliance ? -yMagnitude * maxSpeed : yMagnitude * maxSpeed);
        double angularVelocity = angularMagnitude * maxAngularRate;

        Rotation2d skewCompensationFactor =
                Rotation2d.fromRadians(mCurrentSwerveState.Speeds.omegaRadiansPerSecond * SKEW_COMPENSATION_SCALAR);

        Rotation2d currentRotation = mCurrentSwerveState.Pose.getRotation();
        // TODO: do this in a helper
        return ChassisSpeeds.fromRobotRelativeSpeeds(
                ChassisSpeeds.fromFieldRelativeSpeeds(
                        new ChassisSpeeds(xVelocity, yVelocity, angularVelocity), currentRotation),
                currentRotation.plus(skewCompensationFactor));
    }

    public Command centerLimeLight(Pose2d targetPose2d) {
        return new RunCommand(() -> {
            //centerLimelight(Units.Meters.of(0), Units.Meters.of(0), Units.Radians.of(0), targetPose2d);
            //TODO: integrate limelight center for climber
        }, this);
    }

    public Command joystickDrive(BaseOI controllerOI) {
        return applyRequest(() -> {
            return new SwerveRequest.ApplyFieldSpeeds()
                    .withSpeeds(calculateSpeedsBasedOnJoystickInputs(controllerOI))
                    .withDriveRequestType(DriveRequestType.OpenLoopVoltage)
                    .withDesaturateWheelSpeeds(true);
        });
        // return applyRequest(() -> {
        //     double x = -controllerOI.controller.getLeftY() * maxSpeed;
        //     double y = -controllerOI.controller.getLeftX() * maxSpeed;

        //     double rx = MathUtil.applyDeadband(-controllerOI.controller.getRightX(), 0.3);
        //     double rotationRate = rx * maxAngularRate;

        //     snapToHeading = snapToHeading.plus(new Rotation2d(rotationRate
        //             * (Timer.getFPGATimestamp()
        //                     - lastUpdate))); // TODO: change 0.02 constant timestep to calculate actual timestamp
        //     lastUpdate = Timer.getFPGATimestamp();
        //     Logger.recordOutput("Drivetrain/inRotateMode", rotationRate != 0);
        //     var skewCompensation = currentChassisSpeeds.omegaRadiansPerSecond * -0.03;
        //     snapToHeading = new Rotation2d(currentPose2D.getRotation().getMeasure());
        //     return drive.withVelocityX(MathUtil.applyDeadband(x, 0.1))
        //             .withVelocityY(MathUtil.applyDeadband(y, 0.1))
        //             .withRotationalRate(rotationRate + skewCompensation);
        //     // return driveAndPoint
        //     //         .withVelocityX(MathUtil.applyDeadband(x, 0.1))
        //     //         .withVelocityY(MathUtil.applyDeadband(y, 0.1))
        //     //         .withTargetDirection(snapToHeading);
        // });
    }
    // spotless: on

    public Command driveForDuration(ChassisSpeeds chassisSpeeds, Time time) {
        return new RunCommand(() -> {
                    this.controlRobotDrivetrainAutonomus(chassisSpeeds);
                })
                .withTimeout(time)
                .andThen(this.haltCommand());
    }

    public Command runPath(String pathFileName) {
        var pathBuilder = this.getPathBuilder();
        Path path = new Path(pathFileName);
        return pathBuilder.build(path);
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    public void controlRobotDrivetrainAutonomus(ChassisSpeeds chassisSpeeds) {
        // set desired heading for drivetrain
        this.setControl(
                applyRobotSpeeds.withSpeeds(chassisSpeeds) // Apply the given chassis speed to the drivetrain
                );
    }

    public void halt() {
        this.setControl(
                applyRobotSpeeds.withSpeeds(new ChassisSpeeds()) // Apply the given chassis speed to the drivetrain
                );
    }

    public Limelight getLimelight(String name) {
        // TODO: eventually get the limelights by their names rather than individual getters...
        return limelightLeft;
    }

    public AutoFactory getChoreoAutoFactory() {
        return autoFactory;
    }

    public Command haltCommand() {
        return new RunCommand(() -> halt(), this).withTimeout(0.1);
    }

    public void resetAngle() {
        // this.resetAngle();
    }

    @Override
    public void resetPose(final Pose2d newPose) {
        super.resetPose(newPose);
        this.limelightLeft.setIMUMode(1);
        this.limelightLeft.setRobotOrientation(newPose.getRotation().getMeasure());
    }

    public void setAngle(final Angle angle) {
        super.resetPose(new Pose2d(mCurrentSwerveState.Pose.getTranslation(), new Rotation2d(angle)));
    }

    /**
     * @brief Get the current robot-centric chassis speeds
     *
     * @return the current chassis speeds of the robot
     */
    public ChassisSpeeds getCurrentChassisSpeeds() {
        return currentChassisSpeeds;
    }

    /**
     * @brief Get the current pose
     *
     * @return the current pose of the robot
     */
    public Pose2d getCurrentPose2D() {
        return mCurrentSwerveState.Pose;
    }

    public void runCharacterization(final double volts) {
        for (int i = 0; i < 4; i++) {
            this.getModule(i).getSteerMotor().setControl(new PositionVoltage(Units.Degrees.of(0)));
            this.getModule(i)
                    .getDriveMotor()
                    .setControl(new VoltageOut(volts).withEnableFOC(DriverStation.isAutonomous()));
        }
        Logger.recordOutput("Drivetrain/InputVoltage", volts);
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    public void disabledPeriodic() {
        PoseEstimate mt1 = this.limelightLeft.getPoseMegatag1();
        if (this.limelightLeft.hasValidTargets() && mt1 != null) {
            this.resetRotation(mt1.pose.getRotation());
        }
    }

    public void seedLimelightImu() {
        disabledPeriodic();
    }

    public void setImuMode2() {
        this.limelightLeft.setIMUMode(2);
    }

    // Halts the drive wheels and moves the modules in x formation for maximum traction
    public Command brake() {
        return applyRequest(() -> brake);
    }

    public double getHubX() {
        if (!DriverStation.getAlliance().isEmpty()
                && DriverStation.getAlliance().get() == Alliance.Red) {
            return hubXOffset + hubX;
        } else {
            return hubX;
        }
    }

    // spotless: off
    // Command to aim at hub while moving with max translation speed scaler not deadband (Overrides Rotational aspect)

    public Command aimAtHubAndMove(BaseOI controllerOI, double speedMultipliter) {
        return new ParallelCommandGroup(
                this.applyRequest(() -> driveAndPoint
                        .withVelocityX(-controllerOI.controller.getLeftY()
                                * maxSpeed
                                * speedMultipliter) // Drive forward with negative Y (forward)
                        .withVelocityY(
                                -controllerOI.controller.getLeftX() * maxSpeed * speedMultipliter) // Drive left with negative X (left)
                        .withTargetDirection(new Rotation2d(Math.atan2(
                                                (hubY
                                                        - mCurrentSwerveState
                                                                .Pose
                                                                .getMeasureY()
                                                                .in(Units.Meters)),
                                                (getHubX()
                                                        - mCurrentSwerveState
                                                                .Pose
                                                                .getMeasureX()
                                                                .in(Units.Meters)))
                                        + (!DriverStation.getAlliance().isEmpty()
                                                        && DriverStation.getAlliance()
                                                                        .get()
                                                                != Alliance.Red
                                                ? 0
                                                : 0))
                                .plus(new Rotation2d(Math.PI / 2)))),
                new RunCommand(() -> snapToHeading =
                        new Rotation2d(mCurrentSwerveState.Pose.getRotation().getRadians())));
    }

    public Command aimAtHomeAndMove(BaseOI controllerOI, double speedMultipliter) {
        return new ParallelCommandGroup(
                this.applyRequest(() -> driveAndPoint
                        .withVelocityX(-controllerOI.controller.getLeftY()
                                * maxSpeed
                                * speedMultipliter) // Drive forward with negative Y (forward)
                        .withVelocityY(
                                -controllerOI.controller.getLeftX() * maxSpeed * speedMultipliter) // Drive left with negative X (left)
                        .withTargetDirection(new Rotation2d((DriverStation.getAlliance().get() == Alliance.Red)? Math.PI : 0))),
                new RunCommand(() -> snapToHeading =
                        new Rotation2d(mCurrentSwerveState.Pose.getRotation().getRadians())));
    }

    public Rotation2d getRotationToHub() {
        return new Rotation2d(getAngleToHub(Degrees.of(0)));
    }

    public Angle getAngleToHub(Angle offset) {
        return Units.Radians.of(Math.atan2(
                        (hubY - mCurrentSwerveState.Pose.getMeasureY().in(Units.Meters)),
                        (getHubX() - mCurrentSwerveState.Pose.getMeasureX().in(Units.Meters))))
                .plus(offset);
    }

    public Distance getDistanceFromHub() {

        return Units.Meters.of(Math.hypot(
                (getHubX() - mCurrentSwerveState.Pose.getMeasureX().in(Units.Meters)),
                (hubY - mCurrentSwerveState.Pose.getMeasureY().in(Units.Meters))));
    }

     public void intakeGround(double speedMultiplier) {
        // TODO: get reasonable speed
        // intake.setIntakeSpeed(Tuning.intakeVelocity.get());
        var cont = RobotContainer.getInstance();
            this.setControl(this
                    .driveAndPoint
                    .withVelocityX((cont.joystick1.getLeftX() * speedMultiplier + this.calculateSpeedX())
                            * cont.MaxSpeed)
                    .withVelocityY((cont.joystick1.getLeftY() * speedMultiplier + this.calculateSpeedY())
                            * cont.MaxSpeed));
    }

    public double calculateSpeedX() {
        double output = 0.5;
        Logger.recordOutput("Drivetrain/auto/SpeedXIntakeGroun", output);
        return output;
    }

    public double calculateSpeedY() {
        double output = adjustY.calculate(
                this.limelightLeft.getTargetHorizontalOffset().in(Units.Degrees), 0);
        Logger.recordOutput("Drivetrain/auto/SpeedYIntakeGround", output);
        return output;
    }
    // spotless: on

    // Command to locate fuel and intake them w/ limelight

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters, double timestampSeconds, Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(
                visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Command factory to provide Free Drive operation mode
     *
     * @return A command to operate the drivetrain in free drive mode
     */
    public Command freeDrive() {
        return new InstantCommand(() -> setState(WantedState.TELEOP_DRIVE), this);
    }

    /**
     * Command factory to provide Target Lock operation mode
     *
     * @return A command to operate the drivetrain in target lock mode
     */
    public Command targetLock() {
        return new FunctionalCommand(
            this::initTargetLock,
            () -> {} /* empty execute block; already covered by subsystem periodic */,
            (interrupted) -> {} /* TODO: should probably set brake mode, or no-op depending on interrupt... */,
            this::isAtTargetHeading,
            this
        );
    }

    /**
     * Helper for initializing rotation lock -- sets the desired target based on current pose
     */
    private void initTargetLock() {
        snapToHeading = getRotationToHub();
        setState(WantedState.ROTATION_LOCK);
    }

    /**
     * Helper for checking if we have reached our target heading
     * @return Whether the current heading is within the tolerance of the target heading
     */
    private boolean isAtTargetHeading() {
        Rotation2d rotationalError = mCurrentSwerveState.Pose.getRotation().minus(snapToHeading);
        // TODO: determine appropriate thresholds
        var inRange = Degrees.of(rotationalError.getDegrees()).isNear(Degrees.zero(), Degrees.of(5));
        return inRange;
    }
}
